name: test_config_entorno

on: [push]

jobs:
  configuracion-entorno:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.4
      with:
        node-version: latest
    
    - name: Node version
      run: node --version
    
    - name: Instalacion dependencias
      run: npm install
    
    - name: PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    
    - name: PHP version
      run: php --version
  

